/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as jobEscrowSol from "./jobEscrow.sol";
export type { jobEscrowSol };
import type * as libs from "./libs";
export type { libs };
export type { SkillBridge } from "./SkillBridge";
export type { UserRegistry } from "./UserRegistry";
