/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SkillBridge {
  export type JobListingStruct = {
    id: BigNumberish;
    title: string;
    description: string;
    budget: BigNumberish;
    deadline: BigNumberish;
    client: AddressLike;
    isOpen: boolean;
  };

  export type JobListingStructOutput = [
    id: bigint,
    title: string,
    description: string,
    budget: bigint,
    deadline: bigint,
    client: string,
    isOpen: boolean
  ] & {
    id: bigint;
    title: string;
    description: string;
    budget: bigint;
    deadline: bigint;
    client: string;
    isOpen: boolean;
  };

  export type JobStruct = {
    id: BigNumberish;
    listingId: BigNumberish;
    client: AddressLike;
    provider: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    completedAt: BigNumberish;
    status: BigNumberish;
  };

  export type JobStructOutput = [
    id: bigint,
    listingId: bigint,
    client: string,
    provider: string,
    amount: bigint,
    deadline: bigint,
    completedAt: bigint,
    status: bigint
  ] & {
    id: bigint;
    listingId: bigint;
    client: string;
    provider: string;
    amount: bigint;
    deadline: bigint;
    completedAt: bigint;
    status: bigint;
  };

  export type JobFeedbackStruct = {
    hasClientFeedback: boolean;
    clientApproved: boolean;
    clientComment: string;
    clientRating: BigNumberish;
    hasProviderFeedback: boolean;
    providerComment: string;
    feedbackTimestamp: BigNumberish;
  };

  export type JobFeedbackStructOutput = [
    hasClientFeedback: boolean,
    clientApproved: boolean,
    clientComment: string,
    clientRating: bigint,
    hasProviderFeedback: boolean,
    providerComment: string,
    feedbackTimestamp: bigint
  ] & {
    hasClientFeedback: boolean;
    clientApproved: boolean;
    clientComment: string;
    clientRating: bigint;
    hasProviderFeedback: boolean;
    providerComment: string;
    feedbackTimestamp: bigint;
  };
}

export interface SkillBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLIENT_RESPONSE_GRACE_PERIOD"
      | "addProviderResponse"
      | "allUsers"
      | "applyForJob"
      | "approveWork"
      | "autoRefundMissedDeadline"
      | "autoReleaseAfterGracePeriod"
      | "canAutoRefund"
      | "canAutoRelease"
      | "cancelJob"
      | "clients"
      | "closeJobListing"
      | "emergencyWithdraw"
      | "fundDirectJob"
      | "fundJobFromListing"
      | "getAllClients"
      | "getAllServiceProviders"
      | "getClientJobListings"
      | "getJob"
      | "getJobFeedback"
      | "getJobListing"
      | "getOpenJobListings"
      | "getTimeUntilAutoRelease"
      | "getTimeUntilDeadline"
      | "getTotalUsers"
      | "getUserAverageRating"
      | "getUserJobHistory"
      | "getUserRatingCount"
      | "getUserSkills"
      | "jobApplicants"
      | "jobCounter"
      | "jobFeedbacks"
      | "jobListingCount"
      | "jobListings"
      | "jobs"
      | "markCompleted"
      | "postJobListing"
      | "registerUser"
      | "registeredUsers"
      | "rejectWork"
      | "serviceProviders"
      | "startJob"
      | "updateProfile"
      | "userProfiles"
      | "userRatingCounts"
      | "userRatings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdraw"
      | "JobApplication"
      | "JobApproved"
      | "JobAutoRefunded"
      | "JobAutoReleased"
      | "JobCancelled"
      | "JobCompleted"
      | "JobFunded"
      | "JobListingClosed"
      | "JobListingPosted"
      | "JobRejected"
      | "JobStarted"
      | "ProfileUpdated"
      | "ProviderAssigned"
      | "ProviderFeedbackAdded"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CLIENT_RESPONSE_GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addProviderResponse",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "allUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applyForJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveWork",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "autoRefundMissedDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "autoReleaseAfterGracePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canAutoRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canAutoRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clients",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeJobListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundDirectJob",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundJobFromListing",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllClients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllServiceProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClientJobListings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobFeedback",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenJobListings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUntilAutoRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUntilDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAverageRating",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserJobHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRatingCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSkills",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobApplicants",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "jobFeedbacks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobListingCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "jobListings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markCompleted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "postJobListing",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [string, string, BigNumberish[], string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectWork",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "serviceProviders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [string, string, BigNumberish[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRatingCounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRatings",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CLIENT_RESPONSE_GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addProviderResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "applyForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveWork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoRefundMissedDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoReleaseAfterGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canAutoRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canAutoRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clients", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeJobListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundDirectJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundJobFromListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllClients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllServiceProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClientJobListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getJobFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenJobListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUntilAutoRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUntilDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAverageRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserJobHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRatingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSkills",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobApplicants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobCounter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "jobFeedbacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobListingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postJobListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "serviceProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRatingCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRatings",
    data: BytesLike
  ): Result;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [jobId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [jobId: bigint, refundAmount: bigint];
  export interface OutputObject {
    jobId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobApplicationEvent {
  export type InputTuple = [applicant: AddressLike, listingId: BigNumberish];
  export type OutputTuple = [applicant: string, listingId: bigint];
  export interface OutputObject {
    applicant: string;
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobApprovedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    amountReleased: BigNumberish,
    rating: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    amountReleased: bigint,
    rating: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    amountReleased: bigint;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobAutoRefundedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    refundAmount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    refundAmount: bigint,
    reason: string
  ];
  export interface OutputObject {
    jobId: bigint;
    refundAmount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobAutoReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    amountReleased: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    amountReleased: bigint,
    reason: string
  ];
  export interface OutputObject {
    jobId: bigint;
    amountReleased: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [jobId: bigint, refundAmount: bigint];
  export interface OutputObject {
    jobId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [jobId: BigNumberish, completedAt: BigNumberish];
  export type OutputTuple = [jobId: bigint, completedAt: bigint];
  export interface OutputObject {
    jobId: bigint;
    completedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFundedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    listingId: BigNumberish,
    client: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    listingId: bigint,
    client: string,
    amount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    listingId: bigint;
    client: string;
    amount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobListingClosedEvent {
  export type InputTuple = [listingId: BigNumberish];
  export type OutputTuple = [listingId: bigint];
  export interface OutputObject {
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobListingPostedEvent {
  export type InputTuple = [listingId: BigNumberish, client: AddressLike];
  export type OutputTuple = [listingId: bigint, client: string];
  export interface OutputObject {
    listingId: bigint;
    client: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRejectedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    reason: string,
    rating: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, reason: string, rating: bigint];
  export interface OutputObject {
    jobId: bigint;
    reason: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobStartedEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [userAddress: AddressLike];
  export type OutputTuple = [userAddress: string];
  export interface OutputObject {
    userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderAssignedEvent {
  export type InputTuple = [jobId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [jobId: bigint, provider: string];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderFeedbackAddedEvent {
  export type InputTuple = [jobId: BigNumberish, comment: string];
  export type OutputTuple = [jobId: bigint, comment: string];
  export interface OutputObject {
    jobId: bigint;
    comment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [userAddress: AddressLike, userType: BigNumberish];
  export type OutputTuple = [userAddress: string, userType: bigint];
  export interface OutputObject {
    userAddress: string;
    userType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SkillBridge extends BaseContract {
  connect(runner?: ContractRunner | null): SkillBridge;
  waitForDeployment(): Promise<this>;

  interface: SkillBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLIENT_RESPONSE_GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  addProviderResponse: TypedContractMethod<
    [_jobId: BigNumberish, _response: string],
    [void],
    "nonpayable"
  >;

  allUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  applyForJob: TypedContractMethod<
    [_listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveWork: TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish, _comment: string],
    [void],
    "nonpayable"
  >;

  autoRefundMissedDeadline: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  autoReleaseAfterGracePeriod: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  canAutoRefund: TypedContractMethod<[_jobId: BigNumberish], [boolean], "view">;

  canAutoRelease: TypedContractMethod<
    [_jobId: BigNumberish],
    [boolean],
    "view"
  >;

  cancelJob: TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;

  clients: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  closeJobListing: TypedContractMethod<
    [_listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundDirectJob: TypedContractMethod<
    [_deadline: BigNumberish, _provider: AddressLike],
    [void],
    "payable"
  >;

  fundJobFromListing: TypedContractMethod<
    [_listingId: BigNumberish, _provider: AddressLike],
    [void],
    "payable"
  >;

  getAllClients: TypedContractMethod<[], [string[]], "view">;

  getAllServiceProviders: TypedContractMethod<[], [string[]], "view">;

  getClientJobListings: TypedContractMethod<
    [_clientAddress: AddressLike],
    [SkillBridge.JobListingStructOutput[]],
    "view"
  >;

  getJob: TypedContractMethod<
    [_jobId: BigNumberish],
    [SkillBridge.JobStructOutput],
    "view"
  >;

  getJobFeedback: TypedContractMethod<
    [_jobId: BigNumberish],
    [SkillBridge.JobFeedbackStructOutput],
    "view"
  >;

  getJobListing: TypedContractMethod<
    [_listingId: BigNumberish],
    [SkillBridge.JobListingStructOutput],
    "view"
  >;

  getOpenJobListings: TypedContractMethod<
    [],
    [SkillBridge.JobListingStructOutput[]],
    "view"
  >;

  getTimeUntilAutoRelease: TypedContractMethod<
    [_jobId: BigNumberish],
    [bigint],
    "view"
  >;

  getTimeUntilDeadline: TypedContractMethod<
    [_jobId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalUsers: TypedContractMethod<[], [bigint], "view">;

  getUserAverageRating: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getUserJobHistory: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserRatingCount: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getUserSkills: TypedContractMethod<
    [_userAddress: AddressLike],
    [bigint[]],
    "view"
  >;

  jobApplicants: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  jobCounter: TypedContractMethod<[], [bigint], "view">;

  jobFeedbacks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, boolean, string, bigint, boolean, string, bigint] & {
        hasClientFeedback: boolean;
        clientApproved: boolean;
        clientComment: string;
        clientRating: bigint;
        hasProviderFeedback: boolean;
        providerComment: string;
        feedbackTimestamp: bigint;
      }
    ],
    "view"
  >;

  jobListingCount: TypedContractMethod<[], [bigint], "view">;

  jobListings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, string, boolean] & {
        id: bigint;
        title: string;
        description: string;
        budget: bigint;
        deadline: bigint;
        client: string;
        isOpen: boolean;
      }
    ],
    "view"
  >;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, bigint, bigint] & {
        id: bigint;
        listingId: bigint;
        client: string;
        provider: string;
        amount: bigint;
        deadline: bigint;
        completedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  markCompleted: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  postJobListing: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _budget: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [
      _name: string,
      _email: string,
      _skillCategories: BigNumberish[],
      _location: string,
      _workType: BigNumberish,
      _userType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registeredUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  rejectWork: TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  serviceProviders: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  startJob: TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;

  updateProfile: TypedContractMethod<
    [
      _name: string,
      _email: string,
      _skillCategories: BigNumberish[],
      _location: string,
      _workType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint] & {
        name: string;
        email: string;
        location: string;
        workType: bigint;
        userType: bigint;
      }
    ],
    "view"
  >;

  userRatingCounts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userRatings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLIENT_RESPONSE_GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addProviderResponse"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _response: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "applyForJob"
  ): TypedContractMethod<[_listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveWork"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish, _comment: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "autoRefundMissedDeadline"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "autoReleaseAfterGracePeriod"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canAutoRefund"
  ): TypedContractMethod<[_jobId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "canAutoRelease"
  ): TypedContractMethod<[_jobId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clients"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "closeJobListing"
  ): TypedContractMethod<[_listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundDirectJob"
  ): TypedContractMethod<
    [_deadline: BigNumberish, _provider: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fundJobFromListing"
  ): TypedContractMethod<
    [_listingId: BigNumberish, _provider: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAllClients"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllServiceProviders"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getClientJobListings"
  ): TypedContractMethod<
    [_clientAddress: AddressLike],
    [SkillBridge.JobListingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [SkillBridge.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobFeedback"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [SkillBridge.JobFeedbackStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJobListing"
  ): TypedContractMethod<
    [_listingId: BigNumberish],
    [SkillBridge.JobListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOpenJobListings"
  ): TypedContractMethod<[], [SkillBridge.JobListingStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTimeUntilAutoRelease"
  ): TypedContractMethod<[_jobId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimeUntilDeadline"
  ): TypedContractMethod<[_jobId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAverageRating"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserJobHistory"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserRatingCount"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserSkills"
  ): TypedContractMethod<[_userAddress: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "jobApplicants"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobFeedbacks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, boolean, string, bigint, boolean, string, bigint] & {
        hasClientFeedback: boolean;
        clientApproved: boolean;
        clientComment: string;
        clientRating: bigint;
        hasProviderFeedback: boolean;
        providerComment: string;
        feedbackTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobListingCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobListings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, string, boolean] & {
        id: bigint;
        title: string;
        description: string;
        budget: bigint;
        deadline: bigint;
        client: string;
        isOpen: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, bigint, bigint, bigint] & {
        id: bigint;
        listingId: bigint;
        client: string;
        provider: string;
        amount: bigint;
        deadline: bigint;
        completedAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markCompleted"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "postJobListing"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _budget: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [
      _name: string,
      _email: string,
      _skillCategories: BigNumberish[],
      _location: string,
      _workType: BigNumberish,
      _userType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "rejectWork"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "serviceProviders"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "startJob"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<
    [
      _name: string,
      _email: string,
      _skillCategories: BigNumberish[],
      _location: string,
      _workType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint] & {
        name: string;
        email: string;
        location: string;
        workType: bigint;
        userType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userRatingCounts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userRatings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "JobApplication"
  ): TypedContractEvent<
    JobApplicationEvent.InputTuple,
    JobApplicationEvent.OutputTuple,
    JobApplicationEvent.OutputObject
  >;
  getEvent(
    key: "JobApproved"
  ): TypedContractEvent<
    JobApprovedEvent.InputTuple,
    JobApprovedEvent.OutputTuple,
    JobApprovedEvent.OutputObject
  >;
  getEvent(
    key: "JobAutoRefunded"
  ): TypedContractEvent<
    JobAutoRefundedEvent.InputTuple,
    JobAutoRefundedEvent.OutputTuple,
    JobAutoRefundedEvent.OutputObject
  >;
  getEvent(
    key: "JobAutoReleased"
  ): TypedContractEvent<
    JobAutoReleasedEvent.InputTuple,
    JobAutoReleasedEvent.OutputTuple,
    JobAutoReleasedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobFunded"
  ): TypedContractEvent<
    JobFundedEvent.InputTuple,
    JobFundedEvent.OutputTuple,
    JobFundedEvent.OutputObject
  >;
  getEvent(
    key: "JobListingClosed"
  ): TypedContractEvent<
    JobListingClosedEvent.InputTuple,
    JobListingClosedEvent.OutputTuple,
    JobListingClosedEvent.OutputObject
  >;
  getEvent(
    key: "JobListingPosted"
  ): TypedContractEvent<
    JobListingPostedEvent.InputTuple,
    JobListingPostedEvent.OutputTuple,
    JobListingPostedEvent.OutputObject
  >;
  getEvent(
    key: "JobRejected"
  ): TypedContractEvent<
    JobRejectedEvent.InputTuple,
    JobRejectedEvent.OutputTuple,
    JobRejectedEvent.OutputObject
  >;
  getEvent(
    key: "JobStarted"
  ): TypedContractEvent<
    JobStartedEvent.InputTuple,
    JobStartedEvent.OutputTuple,
    JobStartedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderAssigned"
  ): TypedContractEvent<
    ProviderAssignedEvent.InputTuple,
    ProviderAssignedEvent.OutputTuple,
    ProviderAssignedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderFeedbackAdded"
  ): TypedContractEvent<
    ProviderFeedbackAddedEvent.InputTuple,
    ProviderFeedbackAddedEvent.OutputTuple,
    ProviderFeedbackAddedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdraw(uint256,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "JobApplication(address,uint256)": TypedContractEvent<
      JobApplicationEvent.InputTuple,
      JobApplicationEvent.OutputTuple,
      JobApplicationEvent.OutputObject
    >;
    JobApplication: TypedContractEvent<
      JobApplicationEvent.InputTuple,
      JobApplicationEvent.OutputTuple,
      JobApplicationEvent.OutputObject
    >;

    "JobApproved(uint256,uint256,uint256)": TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;
    JobApproved: TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;

    "JobAutoRefunded(uint256,uint256,string)": TypedContractEvent<
      JobAutoRefundedEvent.InputTuple,
      JobAutoRefundedEvent.OutputTuple,
      JobAutoRefundedEvent.OutputObject
    >;
    JobAutoRefunded: TypedContractEvent<
      JobAutoRefundedEvent.InputTuple,
      JobAutoRefundedEvent.OutputTuple,
      JobAutoRefundedEvent.OutputObject
    >;

    "JobAutoReleased(uint256,uint256,string)": TypedContractEvent<
      JobAutoReleasedEvent.InputTuple,
      JobAutoReleasedEvent.OutputTuple,
      JobAutoReleasedEvent.OutputObject
    >;
    JobAutoReleased: TypedContractEvent<
      JobAutoReleasedEvent.InputTuple,
      JobAutoReleasedEvent.OutputTuple,
      JobAutoReleasedEvent.OutputObject
    >;

    "JobCancelled(uint256,uint256)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobCompleted(uint256,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobFunded(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;
    JobFunded: TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;

    "JobListingClosed(uint256)": TypedContractEvent<
      JobListingClosedEvent.InputTuple,
      JobListingClosedEvent.OutputTuple,
      JobListingClosedEvent.OutputObject
    >;
    JobListingClosed: TypedContractEvent<
      JobListingClosedEvent.InputTuple,
      JobListingClosedEvent.OutputTuple,
      JobListingClosedEvent.OutputObject
    >;

    "JobListingPosted(uint256,address)": TypedContractEvent<
      JobListingPostedEvent.InputTuple,
      JobListingPostedEvent.OutputTuple,
      JobListingPostedEvent.OutputObject
    >;
    JobListingPosted: TypedContractEvent<
      JobListingPostedEvent.InputTuple,
      JobListingPostedEvent.OutputTuple,
      JobListingPostedEvent.OutputObject
    >;

    "JobRejected(uint256,string,uint256)": TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;
    JobRejected: TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;

    "JobStarted(uint256)": TypedContractEvent<
      JobStartedEvent.InputTuple,
      JobStartedEvent.OutputTuple,
      JobStartedEvent.OutputObject
    >;
    JobStarted: TypedContractEvent<
      JobStartedEvent.InputTuple,
      JobStartedEvent.OutputTuple,
      JobStartedEvent.OutputObject
    >;

    "ProfileUpdated(address)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;

    "ProviderAssigned(uint256,address)": TypedContractEvent<
      ProviderAssignedEvent.InputTuple,
      ProviderAssignedEvent.OutputTuple,
      ProviderAssignedEvent.OutputObject
    >;
    ProviderAssigned: TypedContractEvent<
      ProviderAssignedEvent.InputTuple,
      ProviderAssignedEvent.OutputTuple,
      ProviderAssignedEvent.OutputObject
    >;

    "ProviderFeedbackAdded(uint256,string)": TypedContractEvent<
      ProviderFeedbackAddedEvent.InputTuple,
      ProviderFeedbackAddedEvent.OutputTuple,
      ProviderFeedbackAddedEvent.OutputObject
    >;
    ProviderFeedbackAdded: TypedContractEvent<
      ProviderFeedbackAddedEvent.InputTuple,
      ProviderFeedbackAddedEvent.OutputTuple,
      ProviderFeedbackAddedEvent.OutputObject
    >;

    "UserRegistered(address,uint8)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
